// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDSvlCOCawA4hY_n100XmtQ6zCZ0NQQmAk',
    appId: '1:894748319379:web:0b1c2c673c9b90deddb766',
    messagingSenderId: '894748319379',
    projectId: 'nikkuk-fb-auth-bloc',
    authDomain: 'nikkuk-fb-auth-bloc.firebaseapp.com',
    storageBucket: 'nikkuk-fb-auth-bloc.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAdgzx1oAshNTysTJqpQERWASeO_6BrOeQ',
    appId: '1:894748319379:android:f18b1970d94f360addb766',
    messagingSenderId: '894748319379',
    projectId: 'nikkuk-fb-auth-bloc',
    storageBucket: 'nikkuk-fb-auth-bloc.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCrHXczbINVcvOkhx75j0Jb4sOkuUAxQtU',
    appId: '1:894748319379:ios:2cb8106d7b5671deddb766',
    messagingSenderId: '894748319379',
    projectId: 'nikkuk-fb-auth-bloc',
    storageBucket: 'nikkuk-fb-auth-bloc.appspot.com',
    iosClientId: '894748319379-hbhk32r942rf8e49kqsls1id0nm1s0sh.apps.googleusercontent.com',
    iosBundleId: 'com.example.fbAuthBloc',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCrHXczbINVcvOkhx75j0Jb4sOkuUAxQtU',
    appId: '1:894748319379:ios:2cb8106d7b5671deddb766',
    messagingSenderId: '894748319379',
    projectId: 'nikkuk-fb-auth-bloc',
    storageBucket: 'nikkuk-fb-auth-bloc.appspot.com',
    iosClientId: '894748319379-hbhk32r942rf8e49kqsls1id0nm1s0sh.apps.googleusercontent.com',
    iosBundleId: 'com.example.fbAuthBloc',
  );
}
